/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    'src/pages/**/*.{jsx,tsx,ts}',
    'src/common/components/**/*.{jsx,tsx,ts}',
    'src/modules/**/*.{jsx,tsx,ts}',
    'src/layouts/**/*.{jsx,tsx,ts}',
  ],
  theme: {
    extend: {},
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        myLightTheme: {
          primary: '#570df8',
          'primary-content': '#ffffff',
          secondary: '#f000b8',
          'secondary-content': '#ffffff',
          accent: '#37cdbe',
          'accent-content': '#163835',
          neutral: '#3d4451',
          'neutral-content': '#ffffff',
          'base-100': '#ffffff',
          'base-200': '#F2F2F2',
          'base-300': '#E5E6E6',
          'base-content': '#1f2937',
          info: '#3ABFF8',
          'info-content': '#FFFFFF',
          success: '#19B354',
          'success-content': '#FFFFFF',
          warning: '#FBBD23',
          'warning-content': '#FFFFFF',
          error: '#ef4444',
          'error-content': '#FFFFFF',
        },
        myDarkTheme: {
          primary: '#661AE6',
          'primary-content': '#CAD3DD',
          secondary: '#D926AA',
          'secondary-content': '#CAD3DD',
          accent: '#1FB2A5',
          'accent-content': '#CAD3DD',
          neutral: '#191D24',
          'neutral-focus': '#111318',
          'neutral-content': '#A6ADBB',
          'base-100': '#2A303C',
          'base-200': '#242933',
          'base-300': '#20252E',
          'base-content': '#A6ADBB',
        },
      },
    ],
  },
}
